name: Publish Update Site

on:
  push:
    branches:
      - main
    tags:
      - "*.*.*"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build with Maven
      run: >
        xvfb-run
        ./mvnw -B verify --update-snapshots -Pflat-repo

    - name: Upload p2 update site
      uses: actions/upload-artifact@v2
      with:
        name: m2eclipse-egit
        path: org.sonatype.m2e.egit.repository/target/repository/*

    - name: Upload flat p2 update site
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          org.sonatype.m2e.egit.repository/target/flat-repository/*
          
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          org.sonatype.m2e.egit.repository/target/flat-repository/*